import { Experience, Education } from "../types/Data";

export const aboutSection: Array<string> = [
  "Welcome to my page!",
  "I'm Rahul Pavithran, a software engineer specializing in Machine Learning and Cloud Computing, currently based in New Jersey, USA. Prior to my educational relocation, I held the mantle of Senior Software Engineer at ValueLabs, where I dabbled in the mystic arts to build software that help empower businesses.",
  "My journey started at the age of 15 with my first smartphone, the Android-based Moto E 1st Gen. Tinkering with it nurtured my interest in a software engineering career. Over the years, I've had the opportunity to work on various domains and technologies, from a core full stack experience to Blockchain dApps, Cloud, Containers, and eventually cementing myself in Machine Learning and Deep Learning applications, primarily in the field of Image Processing and Computer Vision.",
  "Currently, I'm exploring new opportunities in creating business solutions utilizing Machine Learning capabilities. At other times, I'm usually reading books, exploring Teyvat, or watching Japanese Anime (subtitled of course).",
];

export const expArray: Array<Experience> = [
  {
    dateFrom: "JUN 2022",
    dateTo: "JAN 2023",
    title: "Senior Software Engineer",
    company: "ValueLabs",
    location: "Hyderabad, Telangana, India",
    skills: [
      "Python",
      "Flask",
      "Vue",
      "Airtable",
      "MongoDB",
      "Gitlab",
      "AWS S3",
      "PHP",
      "Magento2",
      "JavaScript",
      "Bitbucket",
      "Jira",
      "Confluence",
    ],
    desc: "Bolstered engineering of critical fixes and documentation across the stack for cloud-based PHP/Magento2 E-commerce website of a prominent dessert brand. Synthesized Flask REST APIs and data migration scripts for AI-based tender aggregator portal hosted on AWS, automating data transfer from AirTable to MongoDB with 35% better efficiency.",
    url: "https://www.valuelabs.com/",
  },
  {
    dateFrom: "JUN 2022",
    dateTo: "JAN 2023",
    title: "Software Engineer",
    company: "ValueLabs",
    location: "Hyderabad, India",
    skills: [
      "Python",
      "Tesseract",
      "JavaScript",
      "Node.js",
      "Express.js",
      "Web3.js",
      "Solidity",
      "Amazon S3",
      "AWS Elastic Beanstalk",
      "Amazon Route 53",
      "Gitlab",
      "Jira",
      "Azure DevOps",
      "Angular",
      "GitHub",
      "Kubernetes (AKS)",
      "CKAN",
      "Docker",
    ],
    desc: "Commanded E2E development of multiple Python-based applications for OCR and document processing. Worked with various cross-functional teams on a diverse set of technologies and niches, including Fullstack, Blockchain and Cloud services on Azure and AWS. Succesfully revived development activities of critical data management portal for an international humanitarian organization to profitability and reduced resource requirements by 50%.",
    url: "https://www.valuelabs.com/",
  },
  {
    dateFrom: "DEC 2019",
    dateTo: "MAR 2020",
    title: "Intern",
    company: "ValueLabs",
    location: "Hyderabad, Telangana, India",
    skills: [
      "ASP.NET MVC",
      "C#",
      "HTML & CSS",
      "xUnit",
      "Entity Framework",
      "Linq",
      "JavaScript",
      "jQuery",
      "KnockoutJS",
      "MySQL",
    ],
    desc: "Strengthened core concepts of OOPS, SOLID Principles and gained understand of system design principles. Composed unit tests for ASP.NET MVC project in production, reducing development load and improving code coverage by 5%.",
    url: "https://www.valuelabs.com/",
  },
  {
    dateFrom: "MAR 2019",
    dateTo: "JUN 2019",
    title: "Machine Learning Engineer - Intern",
    company: "SmartBridge",
    location: "Hyderabad, Telangana, India",
    skills: [
      "Python",
      "NumPy",
      "Pandas",
      "Matplotlib",
      "ML",
      "Jupyter Notebook",
      "Data Visualization",
    ],
    desc: "Mentored over 150 students in Data Analysis, Data Preprocessing, Data Visualization and Machine Learning techniques on Jupyter notebook environment.",
    url: "https://www.thesmartbridge.com/",
  },
  {
    dateFrom: "DEC 2017",
    dateTo: "MAR 2018",
    title: "HPDF Intern",
    company: "Hasura",
    location: "Remote",
    skills: [
      "Python",
      "Flask",
      "JavaScript",
      "CSS",
      "ReactNative",
      "Github",
      "GCP",
    ],
    desc: "Led development team and contributed to frontend development of ReactNative based routing application, harnessing Google's Directions API.",
    url: "https://hasura.io/",
  },
];

export const eduArray: Array<Education> = [
  {
    dateFrom: "JAN 2023",
    dateTo: "MAY 2024",
    title: "MS, Computer Science",
    institute: "New Jersey Institute of Technology",
    location: "Newark, New Jersey, USA",
    gpa: 4.0,
    maxGpa: 4.0,
    relevantCourses: [
      "DSA",
      "DBMS",
      "Image Processing",
      "ML",
      "AI",
      "Computer Networks",
      "OS Design",
      "Cloud Computing",
      "Applied Statistics",
    ],
    url: "https://www.njit.edu/",
  },
  {
    dateFrom: "AUG 2016",
    dateTo: "JUN 2020",
    title: "B.Tech, Computer Science and Engineering",
    institute: "Anurag Group of Institutions",
    location: "Hyderabad, Telangana, India",
    gpa: 9.46,
    maxGpa: 10.0,
    relevantCourses: [
      "C",
      "OOPS (C++)",
      "JAVA",
      "DSA",
      "Web Tech",
      "Logic Design",
      "Computer Architecture",
      "Automata",
      "ML",
      "Computer Networks",
      "OS",
    ],
    url: "https://agi.anurag.edu.in/",
  },
];

export const projArray = [];
