import { Experience, Education, Project } from "./types/Data";

export const aboutSection: Array<string> = [
  "Welcome to my page!",
  "I'm a software engineer specializing in Machine Learning and Cloud Computing, currently based in New Jersey, USA. I perviously held the mantle of Senior Software Engineer at ValueLabs, where I handled end to end development of software solutions that help empower organizations. I had received multiple in-house awards during my tenure for the high impact of my contributions to project delivery.",
  "My journey started at the age of 15 with my first smartphone, the Moto E 1st Gen, and tinkering with its custom ROMs nurtured my interest in software. Over the years, I've had the opportunity to work on various domains and technologies, branching out from a core full stack experience to Blockchain, Cloud, and Machine Learning / Deep Learning applications.",
  "Currently, I'm exploring new opportunities in creating business solutions through the integration of Machine Learning and the best of Software Engineering.",
];

export const expArray: Array<Experience> = [
  {
    dateFrom: "JUN 2022",
    dateTo: "JAN 2023",
    title: "Senior Software Engineer",
    company: "ValueLabs",
    location: "Hyderabad, Telangana, India",
    skills: [
      "Python",
      "Flask",
      "Vue",
      "Airtable",
      "MongoDB",
      "Gitlab",
      "AWS S3",
      "PHP",
      "Adobe Commerce",
      "JavaScript",
      "Bitbucket",
      "Jira",
      "Confluence",
      "New Relic",
    ],
    desc: "Bolstered engineering of critical fixes and documentation across the stack for cloud-based PHP/Magento2 E-commerce website of a prominent dessert brand. Synthesized Flask REST APIs and data migration scripts for AI-based tender aggregator portal hosted on AWS, automating data transfer from AirTable to MongoDB with 28% increase in operational efficiency.",
    url: "https://www.linkedin.com/company/valuelabs/",
  },
  {
    dateFrom: "JUN 2020",
    dateTo: "MAY 2022",
    title: "Software Engineer",
    company: "ValueLabs",
    location: "Hyderabad, Telangana, India",
    skills: [
      "Python",
      "Tesseract",
      "JavaScript",
      "Node.js",
      "Express.js",
      "Web3.js",
      "Solidity",
      "Amazon S3",
      "AWS Elastic Beanstalk",
      "Amazon Route 53",
      "Gitlab",
      "Jira",
      "Azure DevOps",
      "Angular",
      "GitHub Actions",
      "Kubernetes",
      "CKAN",
      "Docker",
    ],
    desc: "Commanded E2E development of multiple Python-based applications for OCR and PDF data extraction. Worked with various cross-functional teams on a diverse set of technologies and niches, including Fullstack, Blockchain and Cloud services on Azure and AWS. Succesfully revived development activities of critical data management portal for an international humanitarian organization to profitability and reduced resource requirements by 48%.",
    url: "https://www.linkedin.com/company/valuelabs/",
  },
  {
    dateFrom: "DEC 2019",
    dateTo: "MAR 2020",
    title: "Intern",
    company: "ValueLabs",
    location: "Hyderabad, Telangana, India",
    skills: [
      "ASP.NET MVC",
      "C#",
      "HTML & CSS",
      "xUnit",
      "JavaScript",
      "jQuery",
      "KnockoutJS",
      "MySQL",
    ],
    desc: "Strengthened core concepts of OOPS, SOLID Principles and gained understand of system design principles. Composed unit tests for ASP.NET MVC project in production, reducing development load and improving code coverage by 5%.",
    url: "https://www.linkedin.com/company/valuelabs/",
  },
  {
    dateFrom: "MAR 2019",
    dateTo: "JUN 2019",
    title: "Machine Learning Engineer - Intern",
    company: "SmartBridge",
    location: "Hyderabad, Telangana, India",
    skills: [
      "Python",
      "NumPy",
      "Pandas",
      "Matplotlib",
      "ML",
      "Jupyter Notebooks",
      "Data Preprocessing",
      "Data Visualization",
      "Machine Learning",
    ],
    desc: "Mentored over 150 students in Data Analysis, Data Preprocessing, Data Visualization and Machine Learning techniques leveraging industry-standard tools and libraries.",
    url: "https://www.linkedin.com/company/smartbridge-educational-services-pvt-ltd/",
  },
  {
    dateFrom: "DEC 2017",
    dateTo: "MAR 2018",
    title: "HPDF Intern",
    company: "Hasura",
    location: "Remote",
    skills: [
      "Python",
      "Flask",
      "JavaScript",
      "CSS",
      "ReactNative",
      "Github",
      "GCP",
    ],
    desc: "Led development team and contributed to frontend development of ReactNative based routing application, harnessing Google's Directions API.",
    url: "https://www.linkedin.com/company/hasura/",
  },
];

export const eduArray: Array<Education> = [
  {
    dateFrom: "JAN 2023",
    dateTo: "MAY 2024",
    title: "MS, Computer Science",
    institute: "New Jersey Institute of Technology",
    location: "Newark, New Jersey, USA",
    gpa: 4.0,
    maxGpa: 4.0,
    relevantCourses: [
      "DSA",
      "DBMS",
      "Image Processing",
      "ML",
      "AI",
      "Computer Networks",
      "OS Design",
      "Cloud Computing",
      "Applied Statistics",
    ],
    url: "https://www.njit.edu/",
  },
  {
    dateFrom: "AUG 2016",
    dateTo: "JUN 2020",
    title: "B.Tech, Computer Science and Engineering",
    institute: "Anurag Group of Institutions",
    location: "Hyderabad, Telangana, India",
    gpa: 9.46,
    maxGpa: 10.0,
    relevantCourses: [
      "C",
      "OOPS (C++)",
      "JAVA",
      "DSA",
      "Web Technologies",
      "Digital Logic Design",
      "Computer Architecture",
      "Software Engineering",
      "Automata",
      "Machine Learning",
      "Computer Networks",
      "OS",
    ],
    url: "https://agi.anurag.edu.in/",
  },
];

export const projArray: Array<Project> = [
  {
    title: "Gaussian Galleria",
    subtitle: "View on GitHub \u2192",
    desc: "Full-stack 3D Scene Management Service to showcase 3D Scene Reconstructions generated via Gaussian Splatting or Neural Radiance Fields (NeRFs). Contributed code as a part of the DiffStudio team.",
    skills: [
      "TypeScript",
      "Next.js",
      "TailwindCSS",
      "Drizzle ORM",
      "PostgreSQL",
      "AWS",
    ],
    url: "https://github.com/naga-k/3D_Portfolio",
  },
  {
    title: "mlinstruct",
    subtitle: "View on GitHub \u2192",
    desc: "Python module for managing ML model training instrances and generating plots for performance metrics developed during my Masters project coursework. Contains additional ML workflow features including early stopping and model checkpointing. This module successfully reduced my asset management and execution efforts by 58%.",
    skills: [
      "Python",
      "Numpy",
      "Matplotlib",
      "scikit-learn",
      "PyTorch",
      "Poetry",
    ],
    url: "https://github.com/alpha2303/mlinstruct/tree/dev",
  },
  {
    title: "pass-man",
    subtitle: "View on GitHub \u2192",
    desc: "Terminal-based multi-vault password manager built in Golang for local storage of domain-based password profiles, secured with AES-256 GCM encryption sequence.",
    skills: ["Golang", "crypto"],
    url: "https://github.com/alpha2303/pass-man",
  },
  {
    title: "Portfolio (2024 Remastered)",
    subtitle: "View on GitHub \u2192",
    desc: "Remastered edition of my portfolio page, built using React + TypeScript and pure CSS.",
    skills: ["TypeScript", "React", "CSS", "Github Actions"],
    url: "https://github.com/alpha2303/alpha2303.github.io",
  },
];
